"""
Domande Quiz - 4 Categorie
Ogni utente riceve una domanda diversa ogni giorno.
40+ domande per categoria per massima varieta.
"""

CATEGORIE = ["gossip", "cultura", "cinema", "musica"]

QUIZ_GOSSIP = [
    {"id": 1, "domanda": "Chi e il marito di Chiara Ferragni?", "risposte": ["Fedez", "Sfera Ebbasta", "J-Ax", "Achille Lauro"], "corretta": 0},
    {"id": 2, "domanda": "Quale coppia si e separata nel 2023 dopo anni di matrimonio social?", "risposte": ["Totti e Ilary", "Ferragni e Fedez", "Hunziker e Trussardi", "Marcuzzi e Calabresi"], "corretta": 0},
    {"id": 3, "domanda": "Come si chiama la figlia di Cristiano Ronaldo e Georgina nata nel 2017?", "risposte": ["Bella", "Alana Martina", "Eva", "Luna"], "corretta": 1},
    {"id": 4, "domanda": "Quanti follower su Instagram ha superato Khaby Lame nel 2023?", "risposte": ["50 milioni", "80 milioni", "150 milioni", "200 milioni"], "corretta": 2},
    {"id": 5, "domanda": "Chi ha vinto il Grande Fratello VIP nella prima edizione?", "risposte": ["Ilary Blasi", "Alessia Macari", "Cecilia Rodriguez", "Luca Onestini"], "corretta": 1},
    {"id": 6, "domanda": "Quale attrice italiana ha sposato Kevin-Prince Boateng?", "risposte": ["Belen Rodriguez", "Melissa Satta", "Elisabetta Canalis", "Giorgia Palmas"], "corretta": 1},
    {"id": 7, "domanda": "Quanti matrimoni ha avuto Pamela Anderson?", "risposte": ["3", "4", "5", "6"], "corretta": 3},
    {"id": 8, "domanda": "Chi e famosa per la frase 'Gemma, apri la busta!'?", "risposte": ["Maria De Filippi", "Barbara D'Urso", "Mara Venier", "Silvia Toffanin"], "corretta": 0},
    {"id": 9, "domanda": "Quale cantante italiano ha avuto una relazione con Belen Rodriguez?", "risposte": ["Tiziano Ferro", "Marco Borriello", "Stefano De Martino", "Fabrizio Corona"], "corretta": 2},
    {"id": 10, "domanda": "In quale reality e apparsa per la prima volta Kim Kardashian?", "risposte": ["The Simple Life", "Keeping Up with the Kardashians", "The Hills", "Paris Hilton Show"], "corretta": 1},
    {"id": 11, "domanda": "Chi e il giudice piu longevo di X Factor Italia?", "risposte": ["Morgan", "Mara Maionchi", "Manuel Agnelli", "Fedez"], "corretta": 1},
    {"id": 12, "domanda": "Quale influencer ha lanciato il brand 'Goovi'?", "risposte": ["Chiara Ferragni", "Michelle Hunziker", "Giulia De Lellis", "Clio Zammatteo"], "corretta": 1},
    {"id": 13, "domanda": "Come si chiama il figlio di Belen e Stefano De Martino?", "risposte": ["Leonardo", "Santiago", "Andrea", "Matteo"], "corretta": 1},
    {"id": 14, "domanda": "Quale ex calciatore e famoso per le storie d'amore mediatiche?", "risposte": ["Del Piero", "Totti", "Vieri", "Pirlo"], "corretta": 2},
    {"id": 15, "domanda": "Chi ha presentato Sanremo per 5 volte consecutive dal 2020?", "risposte": ["Carlo Conti", "Amadeus", "Fiorello", "Baglioni"], "corretta": 1},
    {"id": 16, "domanda": "Quale coppia nata a Uomini e Donne e ancora insieme?", "risposte": ["Costantino e Alessandra", "Eugenio e Francesca", "Aldo e Alessia", "Sossio e Ursula"], "corretta": 3},
    {"id": 17, "domanda": "Quanti figli ha David Beckham?", "risposte": ["2", "3", "4", "5"], "corretta": 2},
    {"id": 18, "domanda": "Quale attrice ha vinto l'Oscar e poi e diventata testimonial di profumi?", "risposte": ["Angelina Jolie", "Nicole Kidman", "Charlize Theron", "Penelope Cruz"], "corretta": 2},
    {"id": 19, "domanda": "Chi e la sorella famosa di Belen Rodriguez?", "risposte": ["Valentina", "Cecilia", "Lucia", "Daniela"], "corretta": 1},
    {"id": 20, "domanda": "Quale conduttrice e soprannominata 'Zia Mara'?", "risposte": ["Mara Venier", "Mara Maionchi", "Mara Carfagna", "Mara Bizzotto"], "corretta": 0},
    {"id": 21, "domanda": "Quante volte si e sposata Jennifer Lopez?", "risposte": ["2", "3", "4", "5"], "corretta": 2},
    {"id": 22, "domanda": "Quale tiktoker italiano e famoso per i video con la nonna?", "risposte": ["Khaby Lame", "Nonna Rosetta (Casa Surace)", "GioPizzi", "Il Milanese Imbruttito"], "corretta": 1},
    {"id": 23, "domanda": "Quale modella e stata soprannominata 'The Body'?", "risposte": ["Naomi Campbell", "Elle Macpherson", "Gisele Bundchen", "Heidi Klum"], "corretta": 1},
    {"id": 24, "domanda": "Chi e il compagno di Diletta Leotta?", "risposte": ["Can Yaman", "Loris Karius", "Daniele Scardina", "Matteo Mammi"], "corretta": 1},
    {"id": 25, "domanda": "Chi ha condotto L'Isola dei Famosi per piu edizioni?", "risposte": ["Simona Ventura", "Alessia Marcuzzi", "Ilary Blasi", "Vladimir Luxuria"], "corretta": 2},
    {"id": 26, "domanda": "Quale calciatore e stato legato sentimentalmente a Shakira?", "risposte": ["Messi", "Pique", "Cristiano Ronaldo", "Neymar"], "corretta": 1},
    {"id": 27, "domanda": "Chi e stata la prima vincitrice del reality Amici di Maria De Filippi?", "risposte": ["Emma Marrone", "Alessandra Amoroso", "Dennis Fantina", "Giulia Stabile"], "corretta": 2},
    {"id": 28, "domanda": "Quale attore e stato sposato sia con Jennifer Aniston che con Angelina Jolie?", "risposte": ["George Clooney", "Brad Pitt", "Matt Damon", "Leonardo DiCaprio"], "corretta": 1},
    {"id": 29, "domanda": "Chi e il padre dei figli di Ilary Blasi?", "risposte": ["Alessandro Nesta", "Francesco Totti", "Daniele De Rossi", "Marco Materazzi"], "corretta": 1},
    {"id": 30, "domanda": "Quale ex gieffina e diventata opinionista fissa al GF?", "risposte": ["Antonella Elia", "Soleil Sorge", "Giulia Salemi", "Stefania Orlando"], "corretta": 0},
    {"id": 31, "domanda": "Chi ha lanciato il brand di moda 'Brave Kid'?", "risposte": ["Chiara Ferragni", "Elisabetta Franchi", "Alberta Ferretti", "Donatella Versace"], "corretta": 0},
    {"id": 32, "domanda": "Quanti figli ha Angelina Jolie in totale?", "risposte": ["3", "4", "5", "6"], "corretta": 3},
    {"id": 33, "domanda": "Quale showgirl e nota per la frase 'Non ce n'e coviddi'?", "risposte": ["Barbara D'Urso", "Angela da Mondello", "Valeria Marini", "Pamela Prati"], "corretta": 1},
    {"id": 34, "domanda": "Chi e il marito di Victoria Beckham?", "risposte": ["David Beckham", "Ryan Giggs", "Gary Neville", "Paul Scholes"], "corretta": 0},
    {"id": 35, "domanda": "Quale cantante ha partecipato a Ballando con le Stelle nel 2023?", "risposte": ["Fedez", "Wanda Nara", "Al Bano", "Gianni Morandi"], "corretta": 1},
    {"id": 36, "domanda": "Come si chiama la figlia di Beyonce e Jay-Z?", "risposte": ["Apple", "North", "Blue Ivy", "Stormi"], "corretta": 2},
    {"id": 37, "domanda": "Quale soubrette e famosa per il 'Mark Caltagirone gate'?", "risposte": ["Valeria Marini", "Pamela Prati", "Carmen Russo", "Sabrina Salerno"], "corretta": 1},
    {"id": 38, "domanda": "Chi e la moglie di Fedez?", "risposte": ["Giulia De Lellis", "Chiara Ferragni", "Aurora Ramazzotti", "Belen Rodriguez"], "corretta": 1},
    {"id": 39, "domanda": "Quale reality americano segue la famiglia Kardashian?", "risposte": ["Real Housewives", "Keeping Up with the Kardashians", "The Bachelor", "Love Island"], "corretta": 1},
    {"id": 40, "domanda": "Chi e il figlio di Eros Ramazzotti e Michelle Hunziker?", "risposte": ["Non hanno figli maschi", "Aurora", "Tommaso", "Non hanno figli insieme"], "corretta": 1},
    {"id": 41, "domanda": "Quale modella brasiliana e nota come 'la piu bella del mondo'?", "risposte": ["Adriana Lima", "Alessandra Ambrosio", "Gisele Bundchen", "Isabeli Fontana"], "corretta": 2},
    {"id": 42, "domanda": "Quale personaggio e stato al centro dello scandalo Pandoro-gate?", "risposte": ["Belen Rodriguez", "Chiara Ferragni", "Elisabetta Canalis", "Melissa Satta"], "corretta": 1},
]

QUIZ_CULTURA = [
    {"id": 1, "domanda": "Quale e la capitale dell'Australia?", "risposte": ["Sydney", "Melbourne", "Canberra", "Perth"], "corretta": 2},
    {"id": 2, "domanda": "Quanti pianeti ha il sistema solare?", "risposte": ["7", "8", "9", "10"], "corretta": 1},
    {"id": 3, "domanda": "In che anno e caduto il Muro di Berlino?", "risposte": ["1987", "1989", "1991", "1993"], "corretta": 1},
    {"id": 4, "domanda": "Quale e l'oceano piu grande del mondo?", "risposte": ["Atlantico", "Indiano", "Pacifico", "Artico"], "corretta": 2},
    {"id": 5, "domanda": "Chi ha dipinto la Gioconda?", "risposte": ["Michelangelo", "Raffaello", "Leonardo da Vinci", "Caravaggio"], "corretta": 2},
    {"id": 6, "domanda": "Qual e il fiume piu lungo del mondo?", "risposte": ["Nilo", "Mississipi", "Rio delle Amazzoni", "Yangtze"], "corretta": 0},
    {"id": 7, "domanda": "In quale paese si trova il Machu Picchu?", "risposte": ["Colombia", "Bolivia", "Peru", "Ecuador"], "corretta": 2},
    {"id": 8, "domanda": "Quante ossa ha il corpo umano adulto?", "risposte": ["186", "206", "226", "256"], "corretta": 1},
    {"id": 9, "domanda": "Quale elemento chimico ha il simbolo 'Au'?", "risposte": ["Argento", "Alluminio", "Oro", "Arsenico"], "corretta": 2},
    {"id": 10, "domanda": "Chi ha scritto La Divina Commedia?", "risposte": ["Petrarca", "Boccaccio", "Dante Alighieri", "Ariosto"], "corretta": 2},
    {"id": 11, "domanda": "Quale paese ha la forma di uno stivale?", "risposte": ["Spagna", "Grecia", "Italia", "Portogallo"], "corretta": 2},
    {"id": 12, "domanda": "Quanti continenti ci sono?", "risposte": ["5", "6", "7", "8"], "corretta": 2},
    {"id": 13, "domanda": "Quale pianeta e conosciuto come il Pianeta Rosso?", "risposte": ["Venere", "Giove", "Marte", "Saturno"], "corretta": 2},
    {"id": 14, "domanda": "In che anno l'uomo e arrivato sulla Luna?", "risposte": ["1965", "1967", "1969", "1971"], "corretta": 2},
    {"id": 15, "domanda": "Quale e la montagna piu alta del mondo?", "risposte": ["K2", "Monte Bianco", "Everest", "Kilimanjaro"], "corretta": 2},
    {"id": 16, "domanda": "Quanti denti ha un adulto?", "risposte": ["28", "30", "32", "34"], "corretta": 2},
    {"id": 17, "domanda": "Quale gas respiriamo principalmente?", "risposte": ["Ossigeno", "Azoto", "Anidride carbonica", "Idrogeno"], "corretta": 1},
    {"id": 18, "domanda": "Chi ha inventato la lampadina?", "risposte": ["Nikola Tesla", "Thomas Edison", "Alexander Bell", "Benjamin Franklin"], "corretta": 1},
    {"id": 19, "domanda": "Quale citta e conosciuta come La Grande Mela?", "risposte": ["Los Angeles", "Chicago", "New York", "San Francisco"], "corretta": 2},
    {"id": 20, "domanda": "Quanti lati ha un pentagono?", "risposte": ["4", "5", "6", "7"], "corretta": 1},
    {"id": 21, "domanda": "In quale continente si trova l'Egitto?", "risposte": ["Asia", "Africa", "Europa", "Medio Oriente"], "corretta": 1},
    {"id": 22, "domanda": "Quale organo del corpo produce l'insulina?", "risposte": ["Fegato", "Reni", "Pancreas", "Stomaco"], "corretta": 2},
    {"id": 23, "domanda": "Quale e la valuta del Giappone?", "risposte": ["Yuan", "Won", "Yen", "Baht"], "corretta": 2},
    {"id": 24, "domanda": "Chi ha scoperto l'America?", "risposte": ["Vasco de Gama", "Magellano", "Cristoforo Colombo", "Amerigo Vespucci"], "corretta": 2},
    {"id": 25, "domanda": "Quante corde ha un violino?", "risposte": ["3", "4", "5", "6"], "corretta": 1},
    {"id": 26, "domanda": "Quale animale e il simbolo dell'Australia?", "risposte": ["Koala", "Canguro", "Ornitorinco", "Emu"], "corretta": 1},
    {"id": 27, "domanda": "In quale citta si trova il Colosseo?", "risposte": ["Atene", "Roma", "Istanbul", "Gerusalemme"], "corretta": 1},
    {"id": 28, "domanda": "Quante lettere ha l'alfabeto italiano?", "risposte": ["21", "24", "26", "28"], "corretta": 0},
    {"id": 29, "domanda": "Quale e il pianeta piu vicino al Sole?", "risposte": ["Venere", "Mercurio", "Terra", "Marte"], "corretta": 1},
    {"id": 30, "domanda": "Chi ha scritto Romeo e Giulietta?", "risposte": ["Dante", "Shakespeare", "Moliere", "Goethe"], "corretta": 1},
    {"id": 31, "domanda": "Quale e il deserto piu grande del mondo?", "risposte": ["Sahara", "Gobi", "Antartico", "Kalahari"], "corretta": 2},
    {"id": 32, "domanda": "Quanti secondi ha un'ora?", "risposte": ["3000", "3200", "3600", "4000"], "corretta": 2},
    {"id": 33, "domanda": "Quale invenzione e attribuita a Guglielmo Marconi?", "risposte": ["Telefono", "Radio", "Televisione", "Telegrafo"], "corretta": 1},
    {"id": 34, "domanda": "Quale e il lago piu grande d'Italia?", "risposte": ["Lago Maggiore", "Lago di Como", "Lago di Garda", "Lago Trasimeno"], "corretta": 2},
    {"id": 35, "domanda": "In quanti stati e divisa l'America?", "risposte": ["48", "50", "51", "52"], "corretta": 1},
    {"id": 36, "domanda": "Quale e la lingua piu parlata al mondo?", "risposte": ["Inglese", "Spagnolo", "Cinese mandarino", "Hindi"], "corretta": 2},
    {"id": 37, "domanda": "Chi ha scritto I Promessi Sposi?", "risposte": ["Leopardi", "Manzoni", "Verga", "D'Annunzio"], "corretta": 1},
    {"id": 38, "domanda": "Quale e l'organo piu grande del corpo umano?", "risposte": ["Fegato", "Cervello", "Pelle", "Intestino"], "corretta": 2},
    {"id": 39, "domanda": "In quale anno e iniziata la Seconda Guerra Mondiale?", "risposte": ["1937", "1938", "1939", "1940"], "corretta": 2},
    {"id": 40, "domanda": "Quale e il metallo piu leggero?", "risposte": ["Alluminio", "Titanio", "Litio", "Magnesio"], "corretta": 2},
    {"id": 41, "domanda": "Quante regioni ha l'Italia?", "risposte": ["18", "19", "20", "21"], "corretta": 2},
    {"id": 42, "domanda": "Quale e il vulcano piu alto d'Europa?", "risposte": ["Vesuvio", "Etna", "Stromboli", "Teide"], "corretta": 1},
]

QUIZ_CINEMA = [
    {"id": 1, "domanda": "Chi interpreta Jack Sparrow nei Pirati dei Caraibi?", "risposte": ["Brad Pitt", "Johnny Depp", "Orlando Bloom", "Leonardo DiCaprio"], "corretta": 1},
    {"id": 2, "domanda": "In quale film si dice 'Io sono tuo padre'?", "risposte": ["Harry Potter", "Il Signore degli Anelli", "Star Wars", "Matrix"], "corretta": 2},
    {"id": 3, "domanda": "Quanti film ci sono nella saga di Harry Potter?", "risposte": ["6", "7", "8", "9"], "corretta": 2},
    {"id": 4, "domanda": "Chi ha diretto Titanic?", "risposte": ["Steven Spielberg", "James Cameron", "Ridley Scott", "Martin Scorsese"], "corretta": 1},
    {"id": 5, "domanda": "Quale attore interpreta Iron Man nel MCU?", "risposte": ["Chris Evans", "Chris Hemsworth", "Robert Downey Jr.", "Mark Ruffalo"], "corretta": 2},
    {"id": 6, "domanda": "In quale serie TV compare Walter White?", "risposte": ["The Wire", "Breaking Bad", "Better Call Saul", "Ozark"], "corretta": 1},
    {"id": 7, "domanda": "Quale film ha vinto l'Oscar come miglior film nel 2020?", "risposte": ["Joker", "1917", "Parasite", "Once Upon a Time in Hollywood"], "corretta": 2},
    {"id": 8, "domanda": "Chi e il protagonista di Forrest Gump?", "risposte": ["Tom Cruise", "Tom Hanks", "Brad Pitt", "Matt Damon"], "corretta": 1},
    {"id": 9, "domanda": "In quale serie si dice 'Winter is coming'?", "risposte": ["Vikings", "The Witcher", "Game of Thrones", "Lord of the Rings"], "corretta": 2},
    {"id": 10, "domanda": "Chi interpreta il Joker nel film del 2019?", "risposte": ["Jared Leto", "Jack Nicholson", "Joaquin Phoenix", "Heath Ledger"], "corretta": 2},
    {"id": 11, "domanda": "Quale serie Netflix parla di rapinatori?", "risposte": ["Narcos", "La Casa di Carta", "Elite", "Vis a Vis"], "corretta": 1},
    {"id": 12, "domanda": "In quale film si dice 'Che la forza sia con te'?", "risposte": ["Star Trek", "Star Wars", "Battlestar Galactica", "Dune"], "corretta": 1},
    {"id": 13, "domanda": "Chi interpreta il Professore ne La Casa di Carta?", "risposte": ["Pedro Alonso", "Alvaro Morte", "Jaime Lorente", "Miguel Herran"], "corretta": 1},
    {"id": 14, "domanda": "Quanti film compongono la saga originale di Star Wars?", "risposte": ["3", "6", "9", "12"], "corretta": 2},
    {"id": 15, "domanda": "Chi e il regista di Pulp Fiction?", "risposte": ["Martin Scorsese", "Quentin Tarantino", "David Lynch", "Coen Brothers"], "corretta": 1},
    {"id": 16, "domanda": "In quale serie ci sono draghi e il Trono di Spade?", "risposte": ["The Witcher", "House of the Dragon", "Game of Thrones", "Merlin"], "corretta": 2},
    {"id": 17, "domanda": "Quale attore ha interpretato sia Rocky che Rambo?", "risposte": ["Schwarzenegger", "Bruce Willis", "Sylvester Stallone", "Van Damme"], "corretta": 2},
    {"id": 18, "domanda": "In Stranger Things, come si chiama il mondo parallelo?", "risposte": ["The Shadow", "The Upside Down", "The Other Side", "The Dark World"], "corretta": 1},
    {"id": 19, "domanda": "Chi ha interpretato il Gladiatore?", "risposte": ["Brad Pitt", "Russell Crowe", "Gerard Butler", "Chris Hemsworth"], "corretta": 1},
    {"id": 20, "domanda": "Quale serie italiana ha avuto successo mondiale?", "risposte": ["Gomorra", "Suburra", "Baby", "Mare Fuori"], "corretta": 0},
    {"id": 21, "domanda": "In quale anno e uscito il primo Matrix?", "risposte": ["1997", "1999", "2001", "2003"], "corretta": 1},
    {"id": 22, "domanda": "Chi interpreta Eleven in Stranger Things?", "risposte": ["Sadie Sink", "Millie Bobby Brown", "Natalia Dyer", "Maya Hawke"], "corretta": 1},
    {"id": 23, "domanda": "Quale attore ha il record di nomination all'Oscar senza mai vincere?", "risposte": ["Brad Pitt", "Leonardo DiCaprio", "Peter O'Toole", "Tom Cruise"], "corretta": 2},
    {"id": 24, "domanda": "In quale film Al Pacino dice 'Say hello to my little friend'?", "risposte": ["Il Padrino", "Scarface", "Heat", "Carlito's Way"], "corretta": 1},
    {"id": 25, "domanda": "Chi ha diretto Il Signore degli Anelli?", "risposte": ["Steven Spielberg", "Peter Jackson", "James Cameron", "Christopher Nolan"], "corretta": 1},
    {"id": 26, "domanda": "Quale serie racconta la storia di un professore di chimica?", "risposte": ["Dexter", "Breaking Bad", "House", "The Wire"], "corretta": 1},
    {"id": 27, "domanda": "Chi interpreta Batman nel film 'Il Cavaliere Oscuro'?", "risposte": ["Ben Affleck", "Christian Bale", "Robert Pattinson", "Michael Keaton"], "corretta": 1},
    {"id": 28, "domanda": "In quale film c'e la frase 'Dopo tutto, domani e un altro giorno'?", "risposte": ["Casablanca", "Via col Vento", "Colazione da Tiffany", "Ben-Hur"], "corretta": 1},
    {"id": 29, "domanda": "Quale regista italiano ha diretto 'La Vita e Bella'?", "risposte": ["Federico Fellini", "Roberto Benigni", "Paolo Sorrentino", "Giuseppe Tornatore"], "corretta": 1},
    {"id": 30, "domanda": "In Squid Game, di che colore sono le tute dei giocatori?", "risposte": ["Blu", "Rosse", "Verdi", "Arancioni"], "corretta": 2},
    {"id": 31, "domanda": "Chi e il protagonista di The Shawshank Redemption?", "risposte": ["Morgan Freeman", "Tim Robbins", "Tom Hanks", "Kevin Spacey"], "corretta": 1},
    {"id": 32, "domanda": "In quale film DiCaprio fa il gesto 'Re del mondo' sulla prua?", "risposte": ["Romeo + Juliet", "Titanic", "The Great Gatsby", "Catch Me If You Can"], "corretta": 1},
    {"id": 33, "domanda": "Chi ha doppiato Buzz Lightyear in italiano in Toy Story?", "risposte": ["Luca Ward", "Massimo Dapporto", "Francesco Pannofino", "Fabio De Luigi"], "corretta": 2},
    {"id": 34, "domanda": "Quale personaggio dice 'Sono inevitabile' nel MCU?", "risposte": ["Loki", "Ultron", "Thanos", "Magneto"], "corretta": 2},
    {"id": 35, "domanda": "In quale serie i protagonisti vivono in un appartamento a New York?", "risposte": ["How I Met Your Mother", "Friends", "Seinfeld", "Tutte queste"], "corretta": 3},
    {"id": 36, "domanda": "Chi ha diretto Inception?", "risposte": ["Christopher Nolan", "Ridley Scott", "Denis Villeneuve", "David Fincher"], "corretta": 0},
    {"id": 37, "domanda": "Quale film di animazione Pixar parla di emozioni nella mente?", "risposte": ["Coco", "Inside Out", "Soul", "Up"], "corretta": 1},
    {"id": 38, "domanda": "Chi interpreta Don Vito Corleone nel primo Padrino?", "risposte": ["Al Pacino", "Robert De Niro", "Marlon Brando", "Joe Pesci"], "corretta": 2},
    {"id": 39, "domanda": "In quale serie c'e il personaggio Omar Little?", "risposte": ["The Sopranos", "Breaking Bad", "The Wire", "Narcos"], "corretta": 2},
    {"id": 40, "domanda": "Chi e il protagonista di John Wick?", "risposte": ["Jason Statham", "Liam Neeson", "Keanu Reeves", "Denzel Washington"], "corretta": 2},
    {"id": 41, "domanda": "Quale film ha la colonna sonora 'My Heart Will Go On'?", "risposte": ["Ghost", "Titanic", "Pretty Woman", "The Bodyguard"], "corretta": 1},
    {"id": 42, "domanda": "In quale serie Netflix la protagonista gioca a scacchi?", "risposte": ["Bridgerton", "The Crown", "La Regina degli Scacchi", "Dark"], "corretta": 2},
]

QUIZ_MUSICA = [
    {"id": 1, "domanda": "Chi ha cantato Bohemian Rhapsody?", "risposte": ["The Beatles", "Led Zeppelin", "Queen", "Pink Floyd"], "corretta": 2},
    {"id": 2, "domanda": "Quale cantante ha vinto Sanremo 2021 con i Maneskin?", "risposte": ["Damiano David", "Thomas Raggi", "Victoria De Angelis", "Ethan Torchio"], "corretta": 0},
    {"id": 3, "domanda": "Quanti membri hanno i Beatles?", "risposte": ["3", "4", "5", "6"], "corretta": 1},
    {"id": 4, "domanda": "Quale cantante e la Regina del Pop?", "risposte": ["Beyonce", "Madonna", "Lady Gaga", "Rihanna"], "corretta": 1},
    {"id": 5, "domanda": "Chi ha cantato Imagine?", "risposte": ["Paul McCartney", "John Lennon", "George Harrison", "Mick Jagger"], "corretta": 1},
    {"id": 6, "domanda": "In quale anno e uscito Thriller di Michael Jackson?", "risposte": ["1980", "1982", "1984", "1986"], "corretta": 1},
    {"id": 7, "domanda": "Quale rapper italiano ha il vero nome Federico Leonardo Lucia?", "risposte": ["Sfera Ebbasta", "Fedez", "Ghali", "Marracash"], "corretta": 1},
    {"id": 8, "domanda": "Chi e il Re del Rock and Roll?", "risposte": ["Chuck Berry", "Elvis Presley", "Little Richard", "Jerry Lee Lewis"], "corretta": 1},
    {"id": 9, "domanda": "Quale band ha cantato Stairway to Heaven?", "risposte": ["Deep Purple", "Black Sabbath", "Led Zeppelin", "AC/DC"], "corretta": 2},
    {"id": 10, "domanda": "Quante corde ha una chitarra classica?", "risposte": ["4", "5", "6", "8"], "corretta": 2},
    {"id": 11, "domanda": "Chi ha vinto l'Eurovision 2021 per l'Italia?", "risposte": ["Mahmood", "Maneskin", "Il Volo", "Diodato"], "corretta": 1},
    {"id": 12, "domanda": "Quale cantante ha il soprannome Il Blasco?", "risposte": ["Ligabue", "Vasco Rossi", "Zucchero", "Eros Ramazzotti"], "corretta": 1},
    {"id": 13, "domanda": "In quale citta si svolge il Festival di Sanremo?", "risposte": ["San Remo", "Sanremo", "Roma", "Milano"], "corretta": 1},
    {"id": 14, "domanda": "Chi ha cantato Shape of You?", "risposte": ["Justin Bieber", "Ed Sheeran", "Bruno Mars", "The Weeknd"], "corretta": 1},
    {"id": 15, "domanda": "Quale strumento suona Jimi Hendrix?", "risposte": ["Batteria", "Basso", "Chitarra", "Tastiera"], "corretta": 2},
    {"id": 16, "domanda": "Chi ha scritto Nel blu dipinto di blu (Volare)?", "risposte": ["Lucio Dalla", "Domenico Modugno", "Adriano Celentano", "Mina"], "corretta": 1},
    {"id": 17, "domanda": "Quale rapper americano si e chiamato Slim Shady?", "risposte": ["Jay-Z", "Kanye West", "Eminem", "50 Cent"], "corretta": 2},
    {"id": 18, "domanda": "Quale nota musicale viene dopo il Do?", "risposte": ["Mi", "Re", "Fa", "Sol"], "corretta": 1},
    {"id": 19, "domanda": "Chi ha cantato Despacito versione originale?", "risposte": ["Enrique Iglesias", "Luis Fonsi", "Daddy Yankee", "J Balvin"], "corretta": 1},
    {"id": 20, "domanda": "Quale cantante italiana e famosa per La solitudine?", "risposte": ["Elisa", "Laura Pausini", "Giorgia", "Gianna Nannini"], "corretta": 1},
    {"id": 21, "domanda": "Quanti tasti ha un pianoforte standard?", "risposte": ["76", "82", "88", "92"], "corretta": 2},
    {"id": 22, "domanda": "Chi e il frontman dei Rolling Stones?", "risposte": ["Keith Richards", "Mick Jagger", "Charlie Watts", "Ron Wood"], "corretta": 1},
    {"id": 23, "domanda": "Quale cantante ha il record di vendite di tutti i tempi?", "risposte": ["Elvis Presley", "Michael Jackson", "The Beatles", "Elton John"], "corretta": 2},
    {"id": 24, "domanda": "Chi ha composto le Quattro Stagioni?", "risposte": ["Mozart", "Beethoven", "Vivaldi", "Bach"], "corretta": 2},
    {"id": 25, "domanda": "Quale cantante e noto come il Principe della canzone?", "risposte": ["Celentano", "Bobby Solo", "Claudio Villa", "Modugno"], "corretta": 2},
    {"id": 26, "domanda": "In quale band cantava Freddie Mercury?", "risposte": ["Pink Floyd", "Queen", "The Who", "Genesis"], "corretta": 1},
    {"id": 27, "domanda": "Quale cantante italiana ha vinto Sanremo con 'Fai Rumore'?", "risposte": ["Elisa", "Giorgia", "Diodato", "Arisa"], "corretta": 2},
    {"id": 28, "domanda": "Chi ha cantato 'Nessun Dorma' facendola conoscere al mondo?", "risposte": ["Andrea Bocelli", "Luciano Pavarotti", "Placido Domingo", "Jose Carreras"], "corretta": 1},
    {"id": 29, "domanda": "Quale genere musicale e nato a Napoli?", "risposte": ["Opera", "Canzone napoletana", "Tarantella", "Tutti questi"], "corretta": 3},
    {"id": 30, "domanda": "Chi ha cantato 'Thriller', l'album piu venduto di sempre?", "risposte": ["Prince", "Michael Jackson", "Whitney Houston", "Stevie Wonder"], "corretta": 1},
    {"id": 31, "domanda": "Quale strumento ha 88 tasti?", "risposte": ["Fisarmonica", "Organo", "Pianoforte", "Clavicembalo"], "corretta": 2},
    {"id": 32, "domanda": "Chi e il cantante dei Coldplay?", "risposte": ["Bono", "Chris Martin", "Thom Yorke", "Brandon Flowers"], "corretta": 1},
    {"id": 33, "domanda": "Quale rapper italiano ha il nome d'arte Sfera Ebbasta?", "risposte": ["Gionata Boschetti", "Federico Lucia", "Amedeo Pagani", "Cosimo Fini"], "corretta": 0},
    {"id": 34, "domanda": "Quale cantante e famosa per 'Like a Virgin'?", "risposte": ["Cyndi Lauper", "Madonna", "Whitney Houston", "Janet Jackson"], "corretta": 1},
    {"id": 35, "domanda": "Chi ha scritto la Nona Sinfonia?", "risposte": ["Mozart", "Beethoven", "Bach", "Haydn"], "corretta": 1},
    {"id": 36, "domanda": "Quale festival musicale si svolge a Glastonbury?", "risposte": ["Rock festival", "Jazz festival", "Pop/Rock festival", "Classical music"], "corretta": 2},
    {"id": 37, "domanda": "Chi ha cantato 'Saliro' a Sanremo?", "risposte": ["Daniele Silvestri", "Mahmood", "Ultimo", "Irama"], "corretta": 0},
    {"id": 38, "domanda": "Quale cantante ha il soprannome 'La Tigre di Cremona'?", "risposte": ["Milva", "Mina", "Ornella Vanoni", "Patty Pravo"], "corretta": 1},
    {"id": 39, "domanda": "Quanti Grammy ha vinto Beyonce (record assoluto)?", "risposte": ["15", "22", "28", "32+"], "corretta": 3},
    {"id": 40, "domanda": "Chi ha cantato 'Purple Rain'?", "risposte": ["David Bowie", "Prince", "George Michael", "Elton John"], "corretta": 1},
    {"id": 41, "domanda": "Quale band ha cantato 'Back in Black'?", "risposte": ["Metallica", "Iron Maiden", "AC/DC", "Guns N' Roses"], "corretta": 2},
    {"id": 42, "domanda": "Chi e il cantante di 'Shallow' con Lady Gaga?", "risposte": ["Bradley Cooper", "Ryan Gosling", "Jake Gyllenhaal", "Chris Pine"], "corretta": 0},
]

QUIZ_PER_CATEGORIA = {
    "gossip": QUIZ_GOSSIP,
    "cultura": QUIZ_CULTURA,
    "cinema": QUIZ_CINEMA,
    "musica": QUIZ_MUSICA,
}

CATEGORIE_INFO = {
    "gossip": {"nome": "GOSSIP", "emoji": "💅", "colore": "#ff69b4"},
    "cultura": {"nome": "CULTURA GENERALE", "emoji": "📚", "colore": "#4fc3f7"},
    "cinema": {"nome": "CINEMA & SERIE TV", "emoji": "🎬", "colore": "#ffa726"},
    "musica": {"nome": "MUSICA", "emoji": "🎵", "colore": "#ab47bc"},
}
