"""
Domande Quiz - 4 Categorie
Ogni utente sceglie una categoria dopo il giro di ruota.
"""

CATEGORIE = ["gossip", "cultura", "cinema", "musica"]

QUIZ_GOSSIP = [
    {"id": 1, "domanda": "Chi e il marito di Chiara Ferragni?", "risposte": ["Fedez", "Sfera Ebbasta", "J-Ax", "Achille Lauro"], "corretta": 0},
    {"id": 2, "domanda": "Quale coppia si e separata nel 2023 dopo anni di matrimonio social?", "risposte": ["Totti e Ilary", "Ferragni e Fedez", "Hunziker e Trussardi", "Marcuzzi e Calabresi"], "corretta": 0},
    {"id": 3, "domanda": "Come si chiama la figlia di Cristiano Ronaldo e Georgina Rodriguez nata nel 2017?", "risposte": ["Bella", "Alana Martina", "Eva", "Luna"], "corretta": 1},
    {"id": 4, "domanda": "Quanti follower su Instagram ha superato Khaby Lame nel 2023?", "risposte": ["50 milioni", "80 milioni", "150 milioni", "200 milioni"], "corretta": 2},
    {"id": 5, "domanda": "Chi ha vinto il Grande Fratello VIP nella prima edizione?", "risposte": ["Ilary Blasi", "Alessia Macari", "Cecilia Rodriguez", "Luca Onestini"], "corretta": 1},
    {"id": 6, "domanda": "Quale attrice italiana ha sposato il calciatore Kevin-Prince Boateng?", "risposte": ["Belen Rodriguez", "Melissa Satta", "Elisabetta Canalis", "Giorgia Palmas"], "corretta": 1},
    {"id": 7, "domanda": "Quanti matrimoni ha avuto Pamela Anderson?", "risposte": ["3", "4", "5", "6"], "corretta": 3},
    {"id": 8, "domanda": "Chi e diventata famosa con la frase 'Gemma, apri la busta!'?", "risposte": ["Maria De Filippi", "Barbara D'Urso", "Mara Venier", "Silvia Toffanin"], "corretta": 0},
    {"id": 9, "domanda": "Quale cantante italiano ha avuto una relazione con Belen Rodriguez?", "risposte": ["Tiziano Ferro", "Marco Borriello", "Stefano De Martino", "Fabrizio Corona"], "corretta": 2},
    {"id": 10, "domanda": "In quale reality show e apparsa per la prima volta Kim Kardashian?", "risposte": ["The Simple Life", "Keeping Up with the Kardashians", "The Hills", "Paris Hilton Show"], "corretta": 1},
    {"id": 11, "domanda": "Chi e il giudice piu longevo di X Factor Italia?", "risposte": ["Morgan", "Mara Maionchi", "Manuel Agnelli", "Fedez"], "corretta": 1},
    {"id": 12, "domanda": "Quale influencer italiana ha lanciato il brand di cosmetici 'Goovi'?", "risposte": ["Chiara Ferragni", "Michelle Hunziker", "Giulia De Lellis", "Clio Zammatteo"], "corretta": 1},
    {"id": 13, "domanda": "Come si chiama il figlio di Belen Rodriguez e Stefano De Martino?", "risposte": ["Leonardo", "Santiago", "Andrea", "Matteo"], "corretta": 1},
    {"id": 14, "domanda": "Quale ex calciatore italiano e famoso per le sue storie d'amore mediatiche?", "risposte": ["Del Piero", "Totti", "Vieri", "Pirlo"], "corretta": 2},
    {"id": 15, "domanda": "Chi ha presentato Sanremo per 5 volte consecutive dal 2020?", "risposte": ["Carlo Conti", "Amadeus", "Fiorello", "Baglioni"], "corretta": 1},
    {"id": 16, "domanda": "Quale coppia e nata nel programma Uomini e Donne ed e ancora insieme?", "risposte": ["Costantino e Alessandra", "Eugenio e Francesca", "Aldo e Alessia", "Sossio e Ursula"], "corretta": 3},
    {"id": 17, "domanda": "Quanti figli ha David Beckham?", "risposte": ["2", "3", "4", "5"], "corretta": 2},
    {"id": 18, "domanda": "Quale attrice ha vinto l'Oscar e poi e diventata testimonial di profumi italiani?", "risposte": ["Angelina Jolie", "Nicole Kidman", "Charlize Theron", "Penelope Cruz"], "corretta": 2},
    {"id": 19, "domanda": "Chi e la sorella famosa di Belen Rodriguez?", "risposte": ["Valentina", "Cecilia", "Lucia", "Daniela"], "corretta": 1},
    {"id": 20, "domanda": "Quale conduttrice italiana e soprannominata 'Zia Mara'?", "risposte": ["Mara Venier", "Mara Maionchi", "Mara Carfagna", "Mara Bizzotto"], "corretta": 0},
    {"id": 21, "domanda": "Quante volte si e sposata Jennifer Lopez?", "risposte": ["2", "3", "4", "5"], "corretta": 2},
    {"id": 22, "domanda": "Quale tiktoker italiano e famoso per i video di cucina con la nonna?", "risposte": ["Khaby Lame", "Nonna Rosetta (Casa Surace)", "GioPizzi", "Il Milanese Imbruttito"], "corretta": 1},
    {"id": 23, "domanda": "Chi ha detto la famosa frase 'Io non ce l'ho con nessuno'?", "risposte": ["Berlusconi", "Fabrizio Corona", "Renzi", "Salvini"], "corretta": 1},
    {"id": 24, "domanda": "Quale modella e stata soprannominata 'The Body'?", "risposte": ["Naomi Campbell", "Elle Macpherson", "Gisele Bundchen", "Heidi Klum"], "corretta": 1},
    {"id": 25, "domanda": "Chi e il compagno di Diletta Leotta?", "risposte": ["Can Yaman", "Loris Karius", "Daniele Scardina", "Matteo Mammì"], "corretta": 1},
]

QUIZ_CULTURA = [
    {"id": 1, "domanda": "Quale e la capitale dell'Australia?", "risposte": ["Sydney", "Melbourne", "Canberra", "Perth"], "corretta": 2},
    {"id": 2, "domanda": "Quanti pianeti ha il sistema solare?", "risposte": ["7", "8", "9", "10"], "corretta": 1},
    {"id": 3, "domanda": "In che anno e caduto il Muro di Berlino?", "risposte": ["1987", "1989", "1991", "1993"], "corretta": 1},
    {"id": 4, "domanda": "Quale e l'oceano piu grande del mondo?", "risposte": ["Atlantico", "Indiano", "Pacifico", "Artico"], "corretta": 2},
    {"id": 5, "domanda": "Chi ha dipinto la Gioconda?", "risposte": ["Michelangelo", "Raffaello", "Leonardo da Vinci", "Caravaggio"], "corretta": 2},
    {"id": 6, "domanda": "Qual e il fiume piu lungo del mondo?", "risposte": ["Nilo", "Mississipi", "Rio delle Amazzoni", "Yangtze"], "corretta": 0},
    {"id": 7, "domanda": "In quale paese si trova il Machu Picchu?", "risposte": ["Colombia", "Bolivia", "Peru", "Ecuador"], "corretta": 2},
    {"id": 8, "domanda": "Quante ossa ha il corpo umano adulto?", "risposte": ["186", "206", "226", "256"], "corretta": 1},
    {"id": 9, "domanda": "Quale elemento chimico ha il simbolo 'Au'?", "risposte": ["Argento", "Alluminio", "Oro", "Arsenico"], "corretta": 2},
    {"id": 10, "domanda": "Chi ha scritto 'La Divina Commedia'?", "risposte": ["Petrarca", "Boccaccio", "Dante Alighieri", "Ariosto"], "corretta": 2},
    {"id": 11, "domanda": "Quale paese ha la forma di uno stivale?", "risposte": ["Spagna", "Grecia", "Italia", "Portogallo"], "corretta": 2},
    {"id": 12, "domanda": "Quanti continenti ci sono?", "risposte": ["5", "6", "7", "8"], "corretta": 2},
    {"id": 13, "domanda": "Quale pianeta e conosciuto come il 'Pianeta Rosso'?", "risposte": ["Venere", "Giove", "Marte", "Saturno"], "corretta": 2},
    {"id": 14, "domanda": "In che anno l'uomo e arrivato sulla Luna?", "risposte": ["1965", "1967", "1969", "1971"], "corretta": 2},
    {"id": 15, "domanda": "Quale e la montagna piu alta del mondo?", "risposte": ["K2", "Monte Bianco", "Everest", "Kilimanjaro"], "corretta": 2},
    {"id": 16, "domanda": "Quanti denti ha un adulto?", "risposte": ["28", "30", "32", "34"], "corretta": 2},
    {"id": 17, "domanda": "Quale gas respiriamo principalmente?", "risposte": ["Ossigeno", "Azoto", "Anidride carbonica", "Idrogeno"], "corretta": 1},
    {"id": 18, "domanda": "Chi ha inventato la lampadina?", "risposte": ["Nikola Tesla", "Thomas Edison", "Alexander Bell", "Benjamin Franklin"], "corretta": 1},
    {"id": 19, "domanda": "Quale citta e conosciuta come 'La Grande Mela'?", "risposte": ["Los Angeles", "Chicago", "New York", "San Francisco"], "corretta": 2},
    {"id": 20, "domanda": "Quanti lati ha un pentagono?", "risposte": ["4", "5", "6", "7"], "corretta": 1},
    {"id": 21, "domanda": "In quale continente si trova l'Egitto?", "risposte": ["Asia", "Africa", "Europa", "Medio Oriente"], "corretta": 1},
    {"id": 22, "domanda": "Quale organo del corpo produce l'insulina?", "risposte": ["Fegato", "Reni", "Pancreas", "Stomaco"], "corretta": 2},
    {"id": 23, "domanda": "Quale e la valuta del Giappone?", "risposte": ["Yuan", "Won", "Yen", "Baht"], "corretta": 2},
    {"id": 24, "domanda": "Chi ha scoperto l'America?", "risposte": ["Vasco de Gama", "Magellano", "Cristoforo Colombo", "Amerigo Vespucci"], "corretta": 2},
    {"id": 25, "domanda": "Quante corde ha un violino?", "risposte": ["3", "4", "5", "6"], "corretta": 1},
]

QUIZ_CINEMA = [
    {"id": 1, "domanda": "Chi interpreta Jack Sparrow nei Pirati dei Caraibi?", "risposte": ["Brad Pitt", "Johnny Depp", "Orlando Bloom", "Leonardo DiCaprio"], "corretta": 1},
    {"id": 2, "domanda": "In quale film si dice 'Io sono tuo padre'?", "risposte": ["Harry Potter", "Il Signore degli Anelli", "Star Wars", "Matrix"], "corretta": 2},
    {"id": 3, "domanda": "Quanti film ci sono nella saga di Harry Potter?", "risposte": ["6", "7", "8", "9"], "corretta": 2},
    {"id": 4, "domanda": "Chi ha diretto Titanic?", "risposte": ["Steven Spielberg", "James Cameron", "Ridley Scott", "Martin Scorsese"], "corretta": 1},
    {"id": 5, "domanda": "Quale attore interpreta Iron Man nel MCU?", "risposte": ["Chris Evans", "Chris Hemsworth", "Robert Downey Jr.", "Mark Ruffalo"], "corretta": 2},
    {"id": 6, "domanda": "In quale serie TV compare il personaggio Walter White?", "risposte": ["The Wire", "Breaking Bad", "Better Call Saul", "Ozark"], "corretta": 1},
    {"id": 7, "domanda": "Quale film ha vinto l'Oscar come miglior film nel 2020?", "risposte": ["Joker", "1917", "Parasite", "Once Upon a Time in Hollywood"], "corretta": 2},
    {"id": 8, "domanda": "Chi e il protagonista di 'Forrest Gump'?", "risposte": ["Tom Cruise", "Tom Hanks", "Brad Pitt", "Matt Damon"], "corretta": 1},
    {"id": 9, "domanda": "In quale serie TV si dice 'Winter is coming'?", "risposte": ["Vikings", "The Witcher", "Game of Thrones", "Lord of the Rings"], "corretta": 2},
    {"id": 10, "domanda": "Chi interpreta il Joker nel film del 2019?", "risposte": ["Jared Leto", "Jack Nicholson", "Joaquin Phoenix", "Heath Ledger"], "corretta": 2},
    {"id": 11, "domanda": "Quale serie Netflix parla di una scuola di rapinatori?", "risposte": ["Narcos", "La Casa di Carta", "Elite", "Vis a Vis"], "corretta": 1},
    {"id": 12, "domanda": "In quale film si trova la frase 'Che la forza sia con te'?", "risposte": ["Star Trek", "Star Wars", "Battlestar Galactica", "Dune"], "corretta": 1},
    {"id": 13, "domanda": "Chi interpreta il Professore ne La Casa di Carta?", "risposte": ["Pedro Alonso", "Alvaro Morte", "Jaime Lorente", "Miguel Herran"], "corretta": 1},
    {"id": 14, "domanda": "Quale attrice italiana ha recitato in film di Hollywood con Woody Allen?", "risposte": ["Monica Bellucci", "Sophia Loren", "Penelope Cruz", "Asia Argento"], "corretta": 2},
    {"id": 15, "domanda": "Quanti film compongono la saga originale di Star Wars?", "risposte": ["3", "6", "9", "12"], "corretta": 2},
    {"id": 16, "domanda": "Chi e il regista di Pulp Fiction?", "risposte": ["Martin Scorsese", "Quentin Tarantino", "David Lynch", "Coen Brothers"], "corretta": 1},
    {"id": 17, "domanda": "In quale serie TV ci sono i draghi e il Trono di Spade?", "risposte": ["The Witcher", "House of the Dragon", "Game of Thrones", "Merlin"], "corretta": 2},
    {"id": 18, "domanda": "Quale attore ha interpretato sia Rocky che Rambo?", "risposte": ["Arnold Schwarzenegger", "Bruce Willis", "Sylvester Stallone", "Jean-Claude Van Damme"], "corretta": 2},
    {"id": 19, "domanda": "In Stranger Things, come si chiama il mondo parallelo?", "risposte": ["The Shadow", "The Upside Down", "The Other Side", "The Dark World"], "corretta": 1},
    {"id": 20, "domanda": "Chi ha interpretato il Gladiatore nell'omonimo film?", "risposte": ["Brad Pitt", "Russell Crowe", "Gerard Butler", "Chris Hemsworth"], "corretta": 1},
    {"id": 21, "domanda": "Quale serie italiana ha avuto successo mondiale su Netflix?", "risposte": ["Gomorra", "Suburra", "Baby", "Mare Fuori"], "corretta": 0},
    {"id": 22, "domanda": "Chi doppia Buzz Lightyear nella versione italiana di Toy Story?", "risposte": ["Luca Ward", "Massimo Dapporto", "Francesco Pannofino", "Fabio De Luigi"], "corretta": 2},
    {"id": 23, "domanda": "In quale anno e uscito il primo film di Matrix?", "risposte": ["1997", "1999", "2001", "2003"], "corretta": 1},
    {"id": 24, "domanda": "Quale serie TV racconta la storia della famiglia Soprano?", "risposte": ["Boardwalk Empire", "The Sopranos", "Goodfellas", "Peaky Blinders"], "corretta": 1},
    {"id": 25, "domanda": "Chi interpreta Eleven in Stranger Things?", "risposte": ["Sadie Sink", "Millie Bobby Brown", "Natalia Dyer", "Maya Hawke"], "corretta": 1},
]

QUIZ_MUSICA = [
    {"id": 1, "domanda": "Chi ha cantato 'Bohemian Rhapsody'?", "risposte": ["The Beatles", "Led Zeppelin", "Queen", "Pink Floyd"], "corretta": 2},
    {"id": 2, "domanda": "Quale cantante italiano ha vinto Sanremo 2021 con i Maneskin?", "risposte": ["Damiano David", "Thomas Raggi", "Victoria De Angelis", "Ethan Torchio"], "corretta": 0},
    {"id": 3, "domanda": "Quanti membri hanno i Beatles?", "risposte": ["3", "4", "5", "6"], "corretta": 1},
    {"id": 4, "domanda": "Quale cantante e conosciuta come 'La Regina del Pop'?", "risposte": ["Beyonce", "Madonna", "Lady Gaga", "Rihanna"], "corretta": 1},
    {"id": 5, "domanda": "Chi ha cantato 'Imagine'?", "risposte": ["Paul McCartney", "John Lennon", "George Harrison", "Mick Jagger"], "corretta": 1},
    {"id": 6, "domanda": "In quale anno e uscito 'Thriller' di Michael Jackson?", "risposte": ["1980", "1982", "1984", "1986"], "corretta": 1},
    {"id": 7, "domanda": "Quale rapper italiano ha il vero nome Federico Leonardo Lucia?", "risposte": ["Sfera Ebbasta", "Fedez", "Ghali", "Marracash"], "corretta": 1},
    {"id": 8, "domanda": "Chi e il 'Re del Rock and Roll'?", "risposte": ["Chuck Berry", "Elvis Presley", "Little Richard", "Jerry Lee Lewis"], "corretta": 1},
    {"id": 9, "domanda": "Quale band ha cantato 'Stairway to Heaven'?", "risposte": ["Deep Purple", "Black Sabbath", "Led Zeppelin", "AC/DC"], "corretta": 2},
    {"id": 10, "domanda": "Quante corde ha una chitarra classica?", "risposte": ["4", "5", "6", "8"], "corretta": 2},
    {"id": 11, "domanda": "Chi ha vinto l'Eurovision 2021 per l'Italia?", "risposte": ["Mahmood", "Maneskin", "Il Volo", "Diodato"], "corretta": 1},
    {"id": 12, "domanda": "Quale cantante ha il soprannome 'Il Blasco'?", "risposte": ["Ligabue", "Vasco Rossi", "Zucchero", "Eros Ramazzotti"], "corretta": 1},
    {"id": 13, "domanda": "In quale citta si svolge il Festival di Sanremo?", "risposte": ["San Remo", "Sanremo", "Roma", "Milano"], "corretta": 1},
    {"id": 14, "domanda": "Chi ha cantato 'Shape of You'?", "risposte": ["Justin Bieber", "Ed Sheeran", "Bruno Mars", "The Weeknd"], "corretta": 1},
    {"id": 15, "domanda": "Quale strumento suona Jimi Hendrix?", "risposte": ["Batteria", "Basso", "Chitarra", "Tastiera"], "corretta": 2},
    {"id": 16, "domanda": "Quanti Grammy ha vinto Beyonce nella sua carriera (record)?", "risposte": ["15", "22", "28", "32+"], "corretta": 3},
    {"id": 17, "domanda": "Chi ha scritto 'Nel blu dipinto di blu' (Volare)?", "risposte": ["Lucio Dalla", "Domenico Modugno", "Adriano Celentano", "Mina"], "corretta": 1},
    {"id": 18, "domanda": "Quale rapper americano si e chiamato 'Slim Shady'?", "risposte": ["Jay-Z", "Kanye West", "Eminem", "50 Cent"], "corretta": 2},
    {"id": 19, "domanda": "In quale decade sono nati gli ABBA?", "risposte": ["Anni 60", "Anni 70", "Anni 80", "Anni 90"], "corretta": 1},
    {"id": 20, "domanda": "Quale nota musicale viene dopo il 'Do'?", "risposte": ["Mi", "Re", "Fa", "Sol"], "corretta": 1},
    {"id": 21, "domanda": "Chi ha cantato 'Despacito' versione originale?", "risposte": ["Enrique Iglesias", "Luis Fonsi", "Daddy Yankee", "J Balvin"], "corretta": 1},
    {"id": 22, "domanda": "Quale cantante italiana e famosa per 'La solitudine'?", "risposte": ["Elisa", "Laura Pausini", "Giorgia", "Gianna Nannini"], "corretta": 1},
    {"id": 23, "domanda": "Quanti tasti ha un pianoforte standard?", "risposte": ["76", "82", "88", "92"], "corretta": 2},
    {"id": 24, "domanda": "Chi e il frontman dei Rolling Stones?", "risposte": ["Keith Richards", "Mick Jagger", "Charlie Watts", "Ron Wood"], "corretta": 1},
    {"id": 25, "domanda": "Quale cantante ha il record di vendite musicali di tutti i tempi?", "risposte": ["Elvis Presley", "Michael Jackson", "The Beatles", "Elton John"], "corretta": 2},
]

QUIZ_PER_CATEGORIA = {
    "gossip": QUIZ_GOSSIP,
    "cultura": QUIZ_CULTURA,
    "cinema": QUIZ_CINEMA,
    "musica": QUIZ_MUSICA,
}

CATEGORIE_INFO = {
    "gossip": {"nome": "GOSSIP", "emoji": "💅", "colore": "#ff69b4"},
    "cultura": {"nome": "CULTURA GENERALE", "emoji": "📚", "colore": "#4fc3f7"},
    "cinema": {"nome": "CINEMA & SERIE TV", "emoji": "🎬", "colore": "#ffa726"},
    "musica": {"nome": "MUSICA", "emoji": "🎵", "colore": "#ab47bc"},
}
