/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/abbonamento` | `/abbonamento`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin` | `/admin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/classifica` | `/classifica`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/comunicazioni` | `/comunicazioni`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/curiosita` | `/curiosita`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/istruttore` | `/istruttore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/premi` | `/premi`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/prenota` | `/prenota`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profilo` | `/profilo`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/abbonamento` | `/abbonamento`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin` | `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/classifica` | `/classifica`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/comunicazioni` | `/comunicazioni`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/curiosita` | `/curiosita`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/istruttore` | `/istruttore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/premi` | `/premi`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/prenota` | `/prenota`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profilo` | `/profilo`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/abbonamento${`?${string}` | `#${string}` | ''}` | `/abbonamento${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/classifica${`?${string}` | `#${string}` | ''}` | `/classifica${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/comunicazioni${`?${string}` | `#${string}` | ''}` | `/comunicazioni${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/curiosita${`?${string}` | `#${string}` | ''}` | `/curiosita${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/istruttore${`?${string}` | `#${string}` | ''}` | `/istruttore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/premi${`?${string}` | `#${string}` | ''}` | `/premi${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/prenota${`?${string}` | `#${string}` | ''}` | `/prenota${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profilo${`?${string}` | `#${string}` | ''}` | `/profilo${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/abbonamento` | `/abbonamento`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin` | `/admin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/classifica` | `/classifica`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/comunicazioni` | `/comunicazioni`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/curiosita` | `/curiosita`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/istruttore` | `/istruttore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/premi` | `/premi`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/prenota` | `/prenota`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profilo` | `/profilo`; params?: Router.UnknownInputParams; };
    }
  }
}
